Repository cse110-sp21-group30/cse110-sp21-group30, pull requests merged in 2021-06, with the labels that each got.

#139 Fixed editor overflow
  source/style.css
Labels: bug

#140 Color theme tests and quick-delete adjustments
  __tests__/script.test.js
  source/bullet-point.js
Labels: enhancement, testing

#143 Reformat color js
  source/color.js
Labels: documentation

#145 Refactored index.html
  source/index.html
  source/router.js
  source/script.js
  source/style.css
Labels: documentation

#147 Refactored style.css + router.js files
  source/index.html
  source/router.js
  source/style.css
Labels: documentation

#150 Removed clear_message line
  source/color.js
Labels: bug
